---
# EXPERIMENTAL PARAMETERS
COLLECT_LOGS : False
COLLECT_TRAINING_DATA : False
USE_INFERENCE_SERVER : False
# NOTE: RISK_MODEL is only valid when INTERVENTION = "Tracing"
RISK_MODEL : "manual" # "naive"  "manual", "digital", "transformer"
SHOULD_MODIFY_BEHAVIOR : True
USE_ORACLE: False

## INTERVENTIONS
INTERVENTION_DAY : 5
# NOTE: INTERVENTION is only valid if INTERVENTION_DAY >= 0
INTERVENTION : "Tracing"
PERCENT_FOLLOW : 1.0
P_HAS_APP : -1.0

# PATHS
CLUSTER_PATH : "output/"

# Inference & Training
TRACING_N_DAYS_HISTORY : 14
DUMP_CLUSTERS : True
CLUSTER_TYPE: "blind" # "old", "blind", "naive", "perfect", "simple"


# TRACING RISK MODEL PARAMETERS  (non-ML)
TRACE_SYMPTOMS : False
TRACE_RISK_UPDATE : False
TRACING_ORDER : 2
UPDATES_PER_DAY : 4
RISK_MAPPING : [0., 0.01, 0.20009698, 0.3337032 , 0.42782824,
                0.53769504, 0.62646553, 0.72454666, 0.79687407, 0.8408014,
                0.87897228, 0.90514533, 0.92788853, 0.94996601, 0.97018845,
                0.98973414, 1.]
